version: '3'
services:
  authors:
    image: lohika/bff-authors-service:1.0
    container_name: bff-authors-service
    networks:
        - mynet
    depends_on:
        - web-sockets

  books:
    image: lohika/bff-books-service:1.0
    container_name: bff-books-service
    networks:
        - mynet    
    depends_on:
        - web-sockets

  web-sockets:
    image: lohika/bff-web-sockets-service:1.0
    container_name: bff-web-sockets-service
    networks:
        - mynet

  mobile-app:
    image: lohika/bff-mobile-app:1.0
    container_name: bff-mobile-app
    ports:
       - 8084:8080
    networks:
        - mynet
    depends_on:
        - web-sockets        

  front-app:
    image: lohika/bff-front-app:1.0
    container_name: bff-front-app
    ports:
       - 8085:8080
    networks:
        - mynet
    depends_on:
        - web-sockets   

  frontend:
      image: lohika/bff-frontend-app:1.0
      container_name: bff-frontend-app
      networks:
          - mynet
      depends_on:
          - authors  
          - books  

  gateway:
      image: lohika/bff-gateway-app:1.0
      container_name: bff-gateway-app
      ports:
         - 8080:8080
      networks:
          - mynet
      depends_on:
          - frontend  

networks:
  mynet:
