server:
  port: 8081
debug: true
auth-token: YWxhZGRpbjpvcGVuc2VzYW1l
spring:
  cloud:
    gateway:
      routes:
        - id: frontend_route
          uri: http://bff-frontend-app:8080/frontend/api/v1/
          predicates:
            - Path=/frontend/api/v1/**
          filters:
            - AuthFilter
        - id: books_route
          uri: http://bff-books-service:8080/api/v1/books
          predicates:
            - Path=/api/v1/books/*
          filters:
            - AuthFilter
        - id: authors_route
          uri: http://bff-authors-service:8080/api/v1/authors
          predicates:
            - Path=/api/v1/authors/*
          filters:
            - AuthFilter