server:
  port: 8081
debug: true
auth-token: YWxhZGRpbjpvcGVuc2VzYW1l
spring:
  redis:
    host: redis
  cloud:
    gateway:
      routes:
        - id: websocket_route
          uri: ws://bff-web-sockets-service:8080/push
          predicates:
            - Path=/push*
        - id: frontend_route
          uri: http://bff-frontend-mobile-app:8080/frontend/api/v1/
          predicates:
            - Path=/frontend/api/v1/**
          filters:
            - AuthFilter
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@apiV1KeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 5
                redis-rate-limiter.requestedTokens: 1
        - id: books_route
          uri: http://bff-books-service:8080/api/v1/books
          predicates:
            - Path=/api/v1/books/*
          filters:
            - AuthFilter
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@apiV1KeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 5
                redis-rate-limiter.requestedTokens: 1
        - id: authors_route
          uri: http://bff-authors-service:8080/api/v1/authors
          predicates:
            - Path=/api/v1/authors/*
          filters:
            - AuthFilter
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@apiV1KeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 5
                redis-rate-limiter.requestedTokens: 1